# Structure of folders and files that will be generated
structure:
  {{.data.baseDir}}:
    index.ts:
      template: templates/Index.gtpl
    providers:
      http:
        index.ts:
          template: templates/ProviderExporter.gtpl

        http_provider.ts:
          template: templates/HttpProvider.gtpl

        fetch_http_provider.ts:
          template: templates/FetchHttpProvider.gtpl

        axios_http_provider.ts:
          template: templates/AxiosHttpProvider.gtpl

        http_provider_interface.ts:
          template: templates/HttpProviderInterface.gtpl
     